# version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx-uikit
    ports:
      - "8085:80"
    restart: always
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html/uikit
    depends_on:
      - php
    networks:
      - uikit_network
  php:
    build:
      context: ./
      dockerfile: ./php/Dockerfile
    tty: true
    working_dir: /var/www/html/uikit
    container_name: php-uikit
    environment:
      PHP_IDE_CONFIG: serverName=uikit.ru
    volumes:
      - ./:/var/www/html/uikit
    networks:
      - uikit_network

networks:
  uikit_network:
    driver: bridge
