services:
  nginx:
    image: nginx:latest
    container_name: nginx-uikit
    ports:
      - "8085:80"
      - "8086:443"
    restart: always
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - PHP_IDE_CONFIG="serverName=uikit"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html/uikit
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - php
    networks:
      - uikit_network
  php:
    build:
      context: ./
      dockerfile: ./php/Dockerfile
    tty: true
    working_dir: /var/www/html/uikit
    container_name: php-uikit
    environment:
      PHP_IDE_CONFIG: serverName=uikit
    volumes:
      - ./:/var/www/html/uikit
    networks:
      - uikit_network
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis-uikit
    ports:
      - "6380:6379"
    networks:
      - uikit_network
    environment:
      PHP_IDE_CONFIG: serverName=uikit


networks:
  uikit_network:
    driver: bridge
