events {
    worker_connections  4096;  ## Default: 1024
}
http {
    include /etc/nginx/mime.types;
    sendfile on;
    #types {
        #application/wasm wasm;
    #}
    server {
        listen 80;
        listen [::]:80;
        server_name localhost;

        #add_header 'Cross-Origin-Opener-Policy' 'same-origin';
        #add_header 'Cross-Origin-Embedder-Policy' 'require-corp';

        root /var/www/html/uikit/public_html;
        index index.php index.html;

        location / {
            #rewrite ^(.*)$ /index.php?path=$1 last;
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            fastcgi_pass php:9000;  # Связь с PHP-контейнером
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        location /static {
            root /var/www/html/uikit/public_html/static;
            expires 1y;
            add_header Pragma public;
            add_header Cache-Control "public";
            fastcgi_hide_header Set-Cookie;
            try_files $uri =404;
        }

        location ~* \.(txt|svg|jpg|jpeg|png)$ {
            root /var/www/html/uikit/public_html;
            expires 30d;
            add_header Cache-Control "public_html";
            add_header  Content-Type text/css;
            #try_files $uri$webp_suffix $uri=404;
            try_files $uri $uri/ /index.php?$query_string;
        }

         location ~ \.js {
             add_header  Content-Type application/x-javascript;
         }

         #location ~* \.wasm$ {
          #   default_type application/wasm;
           #  proxy_hide_header Content-Type;
            # add_header Content-Type application/wasm;
             #proxy_set_header Content-Type application/wasm;
         #}

         error_page 404 /404.php;

        #rewrite ^(.*)$ /index.php?path=$1 last;
    }
    server {
        listen 443 ssl;
        server_name localhost;

        root /var/www/html/uikit/public_html;
        index index.php index.html;

        include    mime.types;
        ssl_certificate     /etc/nginx/certs/localhost.crt;
        ssl_certificate_key /etc/nginx/certs/localhost.key;

        # Other SSL configurations (e.g., ciphers, protocols)
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers 'TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:EECDH+AESGCM:EDH+AESGCM';
        ssl_prefer_server_ciphers on;
        # ssl_verify_client off;

        location / {
           # add_header Content-Security-Policy "script-src 'self' 'unsafe-inline'";
            #rewrite ^(.*)$ /index.php?path=$1 last;
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            fastcgi_pass php:9000;  # Связь с PHP-контейнером
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        location ~* \.(txt|svg|jpg|jpeg|png)$ {
            root /var/www/html/uikit/public_html;
            expires 30d;
            add_header Cache-Control "public_html";
            add_header  Content-Type    text/css;
            #try_files $uri$webp_suffix $uri=404;
            try_files $uri $uri/ /index.php?$query_string;
        }

          location ~ \.js {
              add_header  Content-Type    application/x-javascript;
          }

        #rewrite ^(.*)$ /index.php?path=$1 last;
    }
}